name: HelloWorld
on: [push]
env:
  variable: "Je suis une variable accesible dans tout le workflow"
jobs:
  job1:
    runs-on: ubuntu-latest
    env: 
      variable: "Je suis une variable accesible dans ce job et ses steps"
    steps:
      step1:
        env: 
          variable: "Je suis une variable accesible dans ce step"
    - uses: actions/checkout@v3
    - name: hello world
      run: echo hello world Alexander
