name: PushPull
on: [push]
env:
  variable: "C'est un push fait par Alexander !"
  #variable2: "C'est une pull request !"
jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: push
        run: echo $variable
  #job2:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v3
      #- name: pull
        #run: echo $variable2
on: [pull]
env:
  #variable: "C'est un push fait par Alexander !"
  variable2: "C'est une pull request fait par Fanilo!"
jobs:
  #job1:
    #runs-on: ubuntu-latest
    
    #steps:
      #- uses: actions/checkout@v3
      #- name: push
       # run: echo $variable
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull
        run: echo $variable2
