name: PushPull
on: [push, pull_request]
env:
  variable: "C'est un push fait par Alexander !"
  variable2: "C'est une pull request !"
jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: push
        run: echo $variable
  job2:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: pull
        run: echo $variable2

